~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/red1.bmp -o nitrofiles/card/1/1 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/red2.bmp -o nitrofiles/card/1/2 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/red3.bmp -o nitrofiles/card/1/3 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/red4.bmp -o nitrofiles/card/1/4 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/red5.bmp -o nitrofiles/card/1/5 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/red6.bmp -o nitrofiles/card/1/6 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/red7.bmp -o nitrofiles/card/1/7 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/red8.bmp -o nitrofiles/card/1/8 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/red9.bmp -o nitrofiles/card/1/9 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/red10.bmp -o nitrofiles/card/1/10 -g -gTFF00FF -p -ftb