~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/yel1.bmp -o nitrofiles/card/3/1 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/yel2.bmp -o nitrofiles/card/3/2 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/yel3.bmp -o nitrofiles/card/3/3 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/yel4.bmp -o nitrofiles/card/3/4 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/yel5.bmp -o nitrofiles/card/3/5 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/yel6.bmp -o nitrofiles/card/3/6 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/yel7.bmp -o nitrofiles/card/3/7 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/yel8.bmp -o nitrofiles/card/3/8 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/yel9.bmp -o nitrofiles/card/3/9 -g -gTFF00FF -p -ftb
~/Code/Consoles/nds-dev/_nflib/tools/grit/grit assets/card/yel10.bmp -o nitrofiles/card/3/10 -g -gTFF00FF -p -ftb